### ISSUE TITLE
[ERROR] unable to sign request without credentials set

### ISSUE THREAD

**Issue by klem-ent** [anaynayak/aws-security-viz#109]
Hello,

I'm trying to use the container option to run aws-security-viz. 

I'm running a centos 7.7 with docker 19.03.8, have followed the documentation, everything was working as expected, but when it came to launch the command:
`docker run -i --rm -t -p 3000:3000 -v $(pwd)/aws-viz:/aws-security-viz --name sec-viz sec-viz `

get the following error, and I'm unable to launch the container:

` [ERROR] unable to sign request without credentials set`

Do you know if I miss something? 
I'm new to Docker, so maybe I have to set some creds within docker ...?

**Comment by anaynayak** [comment]
@klem-ent I think you'd have to  pass your AWS access key/secret as environment variables. Something like the following should work.

`docker run -i   -e AWS_ACCESS_KEY_ID=<ACCESS_KEY> -e AWS_SECRET_ACCESS_KEY=<SECRET_KEY>  --rm -t -p 3000:3000 -v $(pwd)/aws-viz:/aws-security-viz --name sec-viz sec-viz`

Let me know if that works for you.

**Comment by klem-ent** [comment]
Hello @anaynayak, thanks for your answer.

The command return nothing. If I'm checking the docker status it return that none docker is running.
Then, I don't know if the command is working fine or not...

**Comment by anaynayak** [comment]
that command should have generated a svg file in the current working directory.
