### ISSUE TITLE
Add `-v` option to print the version

### ISSUE THREAD

**Issue by nunofernandes** [anaynayak/aws-security-viz#119]
It would be awesome to have the `-v` option to print the version of the application.

**Comment by anaynayak** [comment]
That makes a lot of sense @nunofernandes . `-v` is already used for printing the vpc. So would keep it at --version.

**Comment by anaynayak** [comment]
Fixed with https://github.com/anaynayak/aws-security-viz/commit/9d01dbc41a694bea880d25752330f5ba5bd90cfe .
