### ISSUE TITLE
Error when open json file using docker

### ISSUE THREAD

**Issue by dncjkk2** [anaynayak/aws-security-viz#124]
When I run the following command:
`docker run -i --rm -t -p 3000:3000 -v <pwd>/aws-security-viz --name sec-viz sec-viz /usr/local/bundle/bin/aws_security_viz -o <pwd>/aws-describe-security-groups.json --renderer navigator --serve 3000`

The output is that:
`[ERROR] No such file or directory @ rb_sysopen - <pwd>/aws-describe-security-groups.json`

Even I launch the container and use `docker exec` directly, it still get same error.

Any idea on this? Thank you.

**Comment by anaynayak** [comment]
@dncjkk2 I see a few minor typos so want to confirm that the values are actually a bit different when you run them.

Sample command that will run:
`docker run -i --rm -t -p 3000:3000 -v /path/to/current/dir/aws-viz:/aws-security-viz --name sec-viz sec-viz /usr/local/bundle/bin/aws_security_viz -a REPLACE_AWS_ACCESS_KEY_ID -s REPLACE_SECRET --renderer navigator --serve 3000`

The command  mounts `/path/to/current/dir/aws-viz` directory inside the container at `/aws-security-viz`. 

you should move the aws-describe-security-groups.json under /path/to/current/dir/aws-viz so  that  you can pass it to the command as `-o /aws-security-viz/aws-describe-security-groups.json` 

Hoping that helps.

**Comment by dncjkk2** [comment]
@anaynayak It works! Thank you so much!
