### ISSUE TITLE
Issue while installing aws-security-viz on Amazon linux. 

### ISSUE THREAD

**Issue by SriPrasanthG** [anaynayak/aws-security-viz#126]
Hi, Can anyone assist me with the below issue?

[root@ip-172-31-83-4 ec2-user]# gem install aws_security_viz
Successfully installed aws_security_viz-0.2.1
1 gem installed
Installing ri documentation for aws_security_viz-0.2.1...
ERROR:  While executing gem ... (NoMethodError)
    undefined method `map' for Gem::Specification:Class
Did you mean?  tap

**Comment by anaynayak** [comment]
Is this ruby 1.8 by any chance?  The gemspec specifies a minimum of Ruby 2. Alternatively you can do this via [docker](https://github.com/anaynayak/aws-security-viz#docker-usage) .

Also, It isn't necessary to install this on a EC2 box. You can run it locally as well. 

Let me know if either Docker or ruby 2.x doesn't work for you.

**Comment by SriPrasanthG** [comment]
The Ruby version is 2.6 and I later installed the rdoc package and it fixed.
