### ISSUE TITLE
Web view not showing anything

### ISSUE THREAD

**Issue by Mehyar-ALS** [anaynayak/aws-security-viz#143]
Hi,

the web browser is not rendering the JSON file, both in `view.html#nonprod.json` and `navigator.html#nonprod.json`

The JSON file has the data in it, and the SVG works fine.

Thanks.

![image](https://github.com/anaynayak/aws-security-viz/assets/45100231/3c5b2f85-8290-4d3c-bcd1-b710131a8c23)

**Comment by anaynayak** [comment]
@Mehyar-ALS thanks for reporting this. Can you please share the command that was used and the rubygems version?  I'm able to see it working with my aws account so wanted to cross-check.

**Comment by Mehyar-ALS** [comment]
While trying to reproduce the error, I found the problem. Thanks for the replay and willing to help :)
