### ISSUE TITLE
Provide html export

### ISSUE THREAD

**Issue by anaynayak** [anaynayak/aws-security-viz#15]
Follow up from #14 ,  aws-security-viz should provide the capability to export to an interactive html file.

**Comment by garlandkr** [comment]
Hey @anaynayak did you have any time to work on this feature?

**Comment by anaynayak** [comment]
Hi @garlandkr ,

Actually I did. Sadly didnt get to pushing it :( . I am currently working off a temporary laptop. Should be able to push it some time next week.

**Comment by anaynayak** [comment]
I have pushed an initial commit which renders a 'demo.svg' . I still need to think through how to make this easier. I still need to remove the hardcoded demo.svg name and provide a mechanism to serve the view.html page via a webserver.

**Comment by anaynayak** [comment]
I have changed the approach and now no longer rely on the graphviz svg file. This doesn't work very well for larger security group configurations with 500+ nodes. I have shifted over to https://github.com/Linkurious/linkurious.js for rendering the view. 

It now supports highlight of node as well as associated edges and allows you to zoom in.

See screenshot below for details:

<img width="565" alt="html render" src="https://cloud.githubusercontent.com/assets/416211/11912582/0e66cdbc-a669-11e5-82ab-1e26e3c6949b.png">

**Comment by garlandkr** [comment]
I get this when trying to run it:

aws_security_viz -o security_groups.json -f aws.json
```
/Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:508:in `block in output': output format 'aws.json' invalid (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:454:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:454:in `output'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/graph.rb:34:in `output'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/aws_security_viz.rb:41:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/aws_security_viz.rb:20:in `unleash'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/exe/aws_security_viz:28:in `<top (required)>'
	from /usr/bin/aws_security_viz:23:in `load'
	from /usr/bin/aws_security_viz:23:in `<main>'```

**Comment by anaynayak** [comment]
You would have to reinstall the gem using `gem install aws_security_viz --pre`. I haven't released it as a new version yet. 

Once done, the following sequence of commands should work:
```
aws_security_viz -o security_groups.json -f aws.json
python -m SimpleHTTPServer 3000
open 'http://localhost:3000/view.html#aws.json'
```

Let me know if that works for you.

**Comment by garlandkr** [comment]
Same error. Here are my installation steps:

__sudo gem install aws_security_viz --pre__

Fetching: aws_security_viz-0.1.2.pre.alpha.pre.61.gem (100%)
Successfully installed aws_security_viz-0.1.2.pre.alpha.pre.61
Parsing documentation for aws_security_viz-0.1.2.pre.alpha.pre.61
Installing ri documentation for aws_security_viz-0.1.2.pre.alpha.pre.61
1 gem installed

__aws_security_viz -o security_groups.json -f aws.json__

```/Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:508:in `block in output': output format 'aws.json' invalid (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:454:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:454:in `output'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/graph.rb:34:in `output'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/aws_security_viz.rb:41:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/aws_security_viz.rb:20:in `unleash'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/exe/aws_security_viz:28:in `<top (required)>'
	from /usr/bin/aws_security_viz:23:in `load'
	from /usr/bin/aws_security_viz:23:in `<main>'```

Is there an issue with my version of graphiz? Here is the output from **brew info graphviz**:

```
graphviz: stable 2.38.0 (bottled), HEAD
Graph visualization software from AT&T and Bell Labs
http://graphviz.org/
/usr/local/Cellar/graphviz/2.38.0 (469 files, 68M) *
  Built from source with: --with-gts
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/graphviz.rb
==> Dependencies
Build: pkg-config ✔
Required: libpng ✔
Optional: pango ✘, gts ✔, librsvg ✘, freetype ✘
==> Options
--universal
	Build a universal binary
--with-app
	Build GraphViz.app (requires full XCode install)
--with-bindings
	Build Perl/Python/Ruby/etc. bindings
--with-freetype
	Build with freetype support
--with-gts
	Build with GNU GTS support (required by prism)
--with-librsvg
	Build with librsvg support
--with-pango
	Build with Pango/Cairo for alternate PDF output
--with-x11
	Build with x11 support
--HEAD
	Install HEAD version
```

**Comment by anaynayak** [comment]
Your stacktrace suggests that the gem version in use is still 0.1.1

> /Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:508:in `block in output': output format 'aws.json' invalid (ArgumentError)
>    from /Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:454:in `each'
>    from /Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:454:in `output'
>    from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/graph.rb:34:in `output'
>    from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/aws_security_viz.rb:41:in `render'
>    from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/aws_security_viz.rb:20:in `unleash'
>    from /Library/Ruby/Gems/2.0.0/gems/**aws_security_viz-0.1.1**/exe/aws_security_viz:28:in `<top (required)>' 
>    from /usr/bin/aws_security_viz:23:in `load'
>    from /usr/bin/aws_security_viz:23:in `<main>'

I suspect you have multiple versions of the gem installed locally. Can you check where it is being loaded from using `which aws_security_viz` and uninstall + reinstall it ? 

The json renderer bypasses graphviz so the version of graphviz does not matter in this case.

**Comment by garlandkr** [comment]
That was it!

Thanks, looks great.

**Comment by 0x4D31** [comment]
This is awesome! Thanks for adding this feature.

**Comment by anaynayak** [comment]
You are welcome :)
