### ISSUE TITLE
Would love ability to exclude some or all CIDrs

### ISSUE THREAD

**Issue by jdblack** [anaynayak/aws-security-viz#19]
This is great. 

I would love the ability to generate a graph that is able to exclude CIDRs in general, and 0.0.0.0/0 in specific.

**Comment by jdblack** [comment]
At least the ability to ignore output rules, since like many places default to 0.0.0.0/0 for output.

**Comment by anaynayak** [comment]
I've pushed an initial commit which provides this capability. To utilize the same you'll need to define a opts.yml using `aws_security_viz setup opts.yml` 

Once modified to suit your exclusion patterns, run aws-security-viz using:

`aws_security_viz -a your_aws_key -s your_aws_secret_key -f viz.svg -c opts.yml`

Let me know if that works for you.
