### ISSUE TITLE
Fails to produce .json output for webview. Tried on Linux as well as El Capitan. Error included

### ISSUE THREAD

**Issue by jsrichards** [anaynayak/aws-security-viz#20]
System-Name$ aws_security_viz -a <Redacted> -s <Redacted> -f aws.json
/Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:508:in `block in output': output format 'aws.json' invalid (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:454:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/ruby-graphviz-1.2.2/lib/graphviz.rb:454:in `output'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/graph.rb:34:in `output'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/aws_security_viz.rb:41:in `render'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/lib/aws_security_viz.rb:20:in `unleash'
	from /Library/Ruby/Gems/2.0.0/gems/aws_security_viz-0.1.1/exe/aws_security_viz:28:in `<top (required)>'
	from /usr/local/bin/aws_security_viz:23:in `load'
	from /usr/local/bin/aws_security_viz:23:in `<main>'

**Comment by anaynayak** [comment]
The logs suggest that you have aws_security_viz v0.1.1 . The webview output is part of 0.1.2-pre release.

I had forgotten to release a new version of the gem. Thanks for the reminder :) Please try again after updating the gem to v0.1.2

**Comment by jsrichards** [comment]
I got the new gem and it worked! Thank you!

**Comment by anaynayak** [comment]
Cool. Closing this one.
