### ISSUE TITLE
JSON / HTML output doesn't respect destination directiory

### ISSUE THREAD

**Issue by daxbert** [anaynayak/aws-security-viz#26]
When specifying a destination directory for the JSON file, the HTML file is written to the current working directory while the JSON file is written to the specified directory.

Shouldn't these files land in the same specified directory?

How to reproduce:

> \# **mkdir -p /tmp/output/test/path**
> \# **cd /tmp/output/**
> \# **aws_security_viz -o /tmp/aws_security_groups.json -f /tmp/output/test/path/aws.json**
> \# **ls -la /tmp/output/test/path**
> total 92
> drwxr-xr-x. 2 root root  4096 Mar 17 23:24 .
> drwxr-xr-x. 3 root root  4096 Mar 17 23:24 ..
> **-rw-r--r--. 1 root root 83944 Mar 17 23:24 aws.json**
> \# **ls -la .**
> total 20
> drwxr-xr-x. 3 root root 4096 Mar 17 23:24 .
> drwxrwxrwt. 8 root root 4096 Mar 17 23:24 ..
> drwxr-xr-x. 3 root root 4096 Mar 17 23:24 test
> **-rw-r--r--. 1 root root 5539 Mar 17 23:24 view.html**

**Comment by anaynayak** [comment]
Makes sense. Will work on it shortly.

**Comment by anaynayak** [comment]
The file is now written to the same directory as the output file. Thanks for reporting this.
