### ISSUE TITLE
view.html has invalid javascript wrt this.allNeighborsCount

### ISSUE THREAD

**Issue by daxbert** [anaynayak/aws-security-viz#27]
this.allNeighborsCount doesn't exist.  This causes the following error in the console:

view.html:41 Uncaught TypeError: Cannot read property 'default' of undefined

Line 41: 
  return this.allNeighborsCount[nodeId];

Changing to this.neighborCount works

**Comment by anaynayak** [comment]
Thanks for reporting this. I suspect that not locking down the versions for sigma.js might have led to this issue. Will work on fixing this soon.
