### ISSUE TITLE
No longer supports 1.9.3, but gem build script reports otherwise

### ISSUE THREAD

**Issue by 0xf2** [anaynayak/aws-security-viz#31]
aws security viz requires Ruby 2.0, but during the gem install process one sees this message early on:

```
Last (important) changes :
Ruby-Graphviz no longer supports Ruby < 1.9.3
```
before gem fails requiring Ruby 2.0 on 1.9.3.xxxx :) 

Ubuntu 14.04.4. Native main/universe package, no PPA source.

**Comment by anaynayak** [comment]
Thanks for reporting this. Wanted to understand the issue a little bit more.

The message for 1.9.3 is from `Ruby-Graphviz` which is one of gems that I depend upon. I am not sure if I can turn off that message. 

Are you facing issues installing this on Ubuntu 14.04 ?  I was able to test it out on a new VM using steps similar to that specified in the Vagrantfile.

**Comment by 0xf2** [comment]
Ah, my bad -- no issue there then. I thought the < 1.9.3 message was inconsistent as it appears aws-security-viz requires 2.0.

Once 2.0 is set up (on Ubuntu 14.04, not as smooth as one would desire), installing aws-security-viz just works. Thanks for the nice utility!

I am adding mention of aws-security-viz to one of O'Reilly's upcoming titles. If you drop me an email at flucifredi acm org I would love to run the draft of that page by you.

**Comment by anaynayak** [comment]
> Once 2.0 is set up (on Trusty that's not as smooth as one would hope 

As an alternative, you should be able to use the Vagrant VM. A bit of an overkill, but should work consistently. 

> I am adding mention of aws-security-viz to one of O'Reilly's upcoming titles. If you drop me an email at flucifredi acm org I would love to run the draft of that page by you.

👍 🍺 Thanks @0xf2 . You can email me at whynospam-awsviz@yahoo.co.in . It gets routed to my personal account. Looking forward to your email.
