### ISSUE TITLE
Scoped Ingress/Egress graphs

### ISSUE THREAD

**Issue by aabashkin** [anaynayak/aws-security-viz#33]
Great work, I think there is good potential here for scoped, automated threat modeling.

My use case is that given a particular asset (for instance the "App Server" from the README example) I would like to:

- Be able to plot all of the egress points just from that one asset:
![securitygroups_viz_targeted_egress](https://cloud.githubusercontent.com/assets/3102155/22359113/2623384a-e3f9-11e6-8801-b82c5fd2c6eb.png)

- Be able to plot all of the ingress points to that particular asset:
![securitygroups_viz_targeted_ingress](https://cloud.githubusercontent.com/assets/3102155/22359126/3e477238-e3f9-11e6-890b-87f291739996.png)

- Test if the particular asset has access to another particular asset (or set of assets), such as a sensitive/restricted security group.

- Test if this particular asset is reachable by another particular asset (or set of assets), such as the public ELB security group

The commands would probably look like this:

1. `aws_security_viz -o data/security_groups.json -source="app server" -target="*"`
2. `aws_security_viz -o data/security_groups.json -source="*" -target="app server"`
3. `aws_security_viz -o data/security_groups.json -source="app server" -target="restricted-sg"`
4. `aws_security_viz -o data/security_groups.json -source="amazon-elb-sg" -target="app server"`

**It would also be useful to provide a "depth" property. You can scope the results down to 1 hop, 2 hops, or * hops

**Comment by anaynayak** [comment]
@aabashkin that sounds useful. Will work on getting this integrated.

**Comment by anaynayak** [comment]
@aabashkin I have pushed changes which should help get this to a working state.

The parameters are named a bit different. --source-filter and --target-filter. So the following should work:

`bundle exec ruby ./exe/aws_security_viz  -o ../sample_aws.json --target-filter=app server --source-filter=amazon-elb-sg`

This should be available as 0.1.4.pre.alpha.pre.82 gem. Will roll it out to a new version shortly.

**Comment by anaynayak** [comment]
Released as v0.1.4
