### ISSUE TITLE
HTML5 unreadable

### ISSUE THREAD

**Issue by iamfromit** [anaynayak/aws-security-viz#34]
I should be able to generate CSS properties and either link an overriding CSS spreadsheet or override the generated style blocks to increase readability in most situations. How can I do this? The mouse-over/hover magnification doesn't seem to work reliably, and the initial text size makes it a mystery of what object I'll be looking at anyway. All the items in a clicked node/path should be grown to be readable at the same time.

**Comment by anaynayak** [comment]
This has been on my mind for a while now. In some cases the graph contains 3K nodes, and sometimes it is fairly small. This will probably require a fair amount of work. Let me know if you get there sooner with a PR :)

**Comment by anaynayak** [comment]
This should be resolved with the the new `navigator` renderer available in  0.2.0.pre which leverages https://grapheco.github.io/InteractiveGraph for an additional export option. See README for usage instructions.

**Comment by iamfromit** [comment]
Thanks. I will check it out in short order.
