### ISSUE TITLE
Unknown region: "eu-west-3"

### ISSUE THREAD

**Issue by ldb2000** [anaynayak/aws-security-viz#37]
Sounds that the new region eu-west-3 (Paris) is not working

A workaround ?

**Comment by anaynayak** [comment]
@ldb2000  this should now be fixed in the latest master. fog-aws dependency v2.0.1 adds support for the eu-west-3 region. Please reopen the issue if it doesn't work for you.

`gem install aws_security_viz -v 0.1.5.pre.alpha.pre.90 --pre`

**Comment by ldb2000** [comment]
It works perfectly. Thanks a lot!
