### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Hindmalti** [anaynayak/aws-security-viz#74]
Hello ! 

First of all, I want to say great job for this great tool, very useful and easy to set up, nice work!
I have a suggestion to make (maybe you've already thought about it) : possibility to select and view only the ingress or egress for each instance.

Thank you in advance for your answer

**Comment by anaynayak** [comment]
Hello @Hindmalti , Glad you found this of value. 

There are two options currently with which you can filter the data using the `--source-filter` and `--target_filter` parameters. Does that work for your use case ? 

The other option is to filter on the generated web view. 

Let me know if either of these don't work for you.

**Comment by Hindmalti** [comment]
Hello, your welcome ! Your tool is just awsome ! 

I didn't know what to add after the -t or -u flags ( there is no example or 
detailed explanation in the read me :( , and i'm not that good to decipher the ruby >.< ) 

For the web view, I have not seen any option to filter?
But currently , I made a setup and turned the egress to false in the opts.yml

But I'm curious and I'd love to know how your options work, if it is possible ! 
Thank's again for your answer ! 

P.s: sorry for my english ! >.<

**Comment by anaynayak** [comment]
Apologies. You'd have to pass the the -t or -u flags with the instance name (which would also be displayed as a node in the generated graph).

I'll work on adding more examples on the readme so that this is easier the next time.
