### ISSUE TITLE
Document IAM permissions

### ISSUE THREAD

**Issue by rita-liu** [anaynayak/aws-security-viz#86]
Just an enhancement suggestion to docs. It would be great if the required AWS IAM permissions are included in the README.

**Comment by anaynayak** [comment]
Thanks for reporting this @rita-liu  . Will try to add something to the readme. If you have the permissions, please feel free to raise a PR. Otherwise will get to this in the next few days.

**Comment by ABHINAVKISHOREGV** [comment]
Please update IAM permissions @anaynayak. It is difficult to identify it by myself.  
Thank YOU

**Comment by anaynayak** [comment]
I've added a section here https://github.com/anaynayak/aws-security-viz#configuration . The IAM permissions will work for directly configured users only and not for aws-vault.
